import { LoginSignIn } from "./login/page";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | Tailwind CSS",
  description: "Generated by create next app",
};

export default function Page() {
  return <LoginSignIn />;
}
